name: Apache tests
on: [push]
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      wordpress:
        image: wordpress
        env:
          WORDPRESS_DB_HOST: 127.0.0.1
          WORDPRESS_DB_USER: testuser
          WORDPRESS_DB_PASSWORD: testpassword
          WORDPRESS_DB_NAME: testdb
        volumes:
          - /wordpress:/var/www/html
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          composer install

      - name: Execute one secure command
        run: vendor/bin/wp secure add-security-headers --file-path=/wordpress

      - name: Debug
        run: |
          cat /wordpress/.htaccess
          pwd
          docker ps

