name: Apache tests
on: [push]
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    services:
      wordpress:
        image: wordpress
        env:
          WORDPRESS_DB_HOST: localhost
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: root
          WORDPRESS_DB_NAME: testdb
        volumes:
          - /wordpress:/var/www/html
        ports:
          - 8080:80
        options:
          --name wordpress
    env:
      DB_DATABASE: testdb
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - name: Start MYSQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Resrtart WordPress container
        run: docker restart wordpress

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          composer install

      - name: Execute one secure command
        run: vendor/bin/wp secure add-security-headers

      - name: Debug
        run: |
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} testdb <<< 'SHOW TABLES'

