name: Apache tests
on: [push]
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "rootpass"
          MYSQL_USER: "wordpress"
          MYSQL_PASSWORD: "wordpress"
          MYSQL_DATABASE: "wordpress"
        ports:
          - 3306:3306
        options: >-
          --mount type=tmpfs,destination=/var/lib/mysql
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      wordpress:
        image: wordpress
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress
        ports:
          - 8080:80
        options:
          --name wordpress -v ${{ github.workspace }}/wordpress:/var/www/html
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'codebase'
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/codebase && composer install

      - name: Make .htaccess writebable
        run: |
          sudo chmod 666 ${{ github.workspace }}/wordpress/.htaccess

      - name: Execute one secure command
        run: sudo codebase/vendor/bin/wp secure block-access sensitive-files --file-path=${{ github.workspace }}/wordpress/.htaccess --allow-root

      - name: Debug
        run: |
          curl -I http://localhost:8080/readme.html

