name: Apache tests
on: [push]
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    services:
      wordpress:
        image: wordpress
        env:
          WORDPRESS_DB_HOST: host.docker.internal
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: root
          WORDPRESS_DB_NAME: testdb
        volumes:
          - wordpress:/var/www/html
        ports:
          - 8080:80
        options:
          --name wordpress
    env:
      DB_DATABASE: testdb
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - name: Start MYSQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          composer install

#      - name: Setup WordPress configuration
#        run: |
#          vendor/bin/wp config create --dbname=${{ env.DB_DATABASE }} --dbuser=${{ env.DB_USER }} --dbpass=${{ env.DB_PASSWORD }} --dbhost=localhost --force --path=wordpress

      - name: Restart WordPress container
        run: docker restart wordpress

#      - name: Install WordPress
#        run: |
#          vendor/bin/wp core install --url=http://localhost --title="WordPress" --admin_user=admin --admin_email=admin@example.com --admin_password=pass --skip-email  --path=wordpress

      - name: Execute one secure command
        run: vendor/bin/wp secure add-security-headers

      - name: Debug
        run: |
          vendor/bin/wp plugin list --path=wordpress

