---
name: Web server integration tests

on:
  pull_request:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ddev
        uses: jonaseberle/github-action-setup-ddev@v1
        run: ddev --help
#    services:
#      mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_DATABASE: testdb
#          MYSQL_USER: testdb
#          MYSQL_PASSWORD: mysqlpass
#          MYSQL_ROOT_PASSWORD: mysqlpass
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3